FROM us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.16.5

RUN apt update && apt install curl zstd -y
# Copy the check_sync_status.sh script into the container
COPY download-consensus-layer-files.sh /usr/local/bin/download-consensus-layer-files.sh

# Make the script executable
RUN chmod +x /usr/local/bin/download-consensus-layer-files.sh

ENTRYPOINT ["/usr/local/bin/download-consensus-layer-files.sh"]