FROM us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.16.5 AS opnode

FROM ubuntu:latest

COPY --from=opnode /usr/local/bin/op-node /usr/local/bin/

RUN apt update && apt install curl zstd jq -y
# Copy the check_sync_status.sh script into the container
COPY download-consensus-layer-files.sh /usr/local/bin/download-consensus-layer-files.sh

# Make the script executable
RUN chmod +x /usr/local/bin/download-consensus-layer-files.sh

ENTRYPOINT ["/usr/local/bin/download-consensus-layer-files.sh"]
